### ISSUE TITLE
Sender email

### ISSUE THREAD

**Issue by tdenof** [korween/centralink#22]
Add a form for user's mail.
But need changes in node-mailer too.

**Comment by nymous** [comment]
This would be used if the poster wants an answer.
There then should be a button in the centralink.

**Comment by korween** [comment]
The poster can write down the email, and it will be transformed into a mail:to by linky.
The only reason this existed in the previous implementation is because it wasn't possible to render a clickable link outside of the button.

Please stop referring to the old version for your design "ideas" without thinking about ergonomy and UX first. 

Feature request closed for not being innovative.
